name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  Buildandpushdocker:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: gitclone 
        run: git clone https://github.com/Shubhambawa98/testenv.git
      - name: docker installation 
        run: curl -fsSL https://get.docker.com | sh 
      - name: docker login 
        run: docker login -u ${{secrets.DOCKERHUBUSERNAME}} -p ${{secrets.DOCKERHUBPASSWORD}}
      - name: docker build 
        run: cd testenv && docker build . -t fast_api
      - name: test
        run: echo "hello"
      - name: docker tag  
        run: docker tag fast_api fast_api:latest
      - name: docker image name list
        run: docker image ls
      - name: docker push  
        run: docker push jesz88/fast_api:latest
